"""Added Item model.

Revision ID: 0d640a71cba9
Revises: be3ab8ecf001
Create Date: 2020-08-17 10:18:34.235987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d640a71cba9'
down_revision = 'be3ab8ecf001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=56), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('looking_for', 'found', name='reason'), nullable=False),
    sa.Column('looking_for_reason', sa.Enum('lost', 'stolen', 'other', name='lookingforreason'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("NOT(reason = 'Looking For' and looking_for_reason IS NULL)", name='ck_item_looking_for_reason'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_item_category_id_category')),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_item_created_by_id_user')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_item_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('slug', name=op.f('uq_item_slug'))
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_reason'), ['reason'], unique=False)

    op.create_table('item_image',
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_item_image_created_by_id_user')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_image_item_id_item')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_item_image_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_image')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_reason'))

    op.drop_table('item')
    # ### end Alembic commands ###
