"""Added BaseModel.

Revision ID: 13fbb573f2c6
Revises: 725a6a465e38
Create Date: 2020-08-13 10:07:32.409384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fbb573f2c6'
down_revision = '725a6a465e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_on', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_on')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_on')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
