"""Made Category name unique.

Revision ID: 66712593f188
Revises: 0d640a71cba9
Create Date: 2020-08-17 12:49:59.824243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66712593f188'
down_revision = '0d640a71cba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    # ### end Alembic commands ###
