"""Added Category.

Revision ID: be3ab8ecf001
Revises: 1ee77169f6f6
Create Date: 2020-08-14 12:32:57.922000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3ab8ecf001'
down_revision = '1ee77169f6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_category_created_by_id_user')),
    sa.ForeignKeyConstraint(['parent_category_id'], ['category.id'], name=op.f('fk_category_parent_category_id_category')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_category_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
    sa.UniqueConstraint('slug', name=op.f('uq_category_slug'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
